[package]
org = "ballerinax"
name = "apim_catalog_tests"
version = "1.0.0"

[[dependency]]
org = "ballerinax"
name = "wso2.apim.catalog"
version = "1.0.0"
repository="local"

[build-options]
remoteManagement=true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina"
artifactId = "wso2.apim.catalog-native"
version = "1.0.0"
path = "../native/build/libs/wso2.apim.catalog-native-1.0.0.jar"
