[package]
org = "admin"
name = "sample_project_6"
version = "0.1.0"
distribution = "2201.10.0"

[[dependency]]
org = "ballerinax"
name = "wso2.apim.catalog"
version = "1.1.0"
repository="local"

[build-options]
remoteManagement=true
